[versions]
agp = "8.6.1"
jsoup = "1.18.1"
appcompat = "1.7.0"
material = "1.12.0"
picasso = "2.8"

[libraries]
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }